### ISSUE TITLE
Suggestion for Page Collection doc

### ISSUE THREAD

**Issue by martinsik** [getgrav/grav-learn#221]
For me as somebody who's never used Grav before was quite confusing what's [Page Collections](http://learn.getgrav.org/content/collections) documentation talking about and how can I use it.
After digging in Antimatter's source code I found out that it defines what I get after calling `page.collection()` which I'd expect to be mentioned in [Page Collections](http://learn.getgrav.org/content/collections) or at least in [Twig Filters & Functions](http://learn.getgrav.org/themes/twig-filters-functions).

This is more like a suggestion that an issue :).

**Comment by Vivalldi** [comment]
Hello @martinsik may I suggest making editing the page in it's repository and making a PR?

https://github.com/getgrav/grav-learn/blob/develop/pages/02.content/03.collections/docs.md

I'm sure the grav team would appreciate it.

**Comment by martinsik** [comment]
Hey, sorry for my delay. I'll have a look at it.

**Comment by kmcital** [comment]
I agree with this, I'm having a hard time right now figuring out how to work with page collections. I've got the header variables set, but it is not clear how to produce the page list of results. In some skeleton examples I don't see a twig template that does the work, and in others I do. The documentation could really be improved on this topic since I'm lost.
