### ISSUE TITLE
Please add CONTRAST to make the site better readable.

### ISSUE THREAD

**Issue by COLABORATI** [getgrav/grav-learn#273]
Please no more light grey font on white background - it hurts the eyes. Please add strong contrast to make the learn site better readable, thank you! Also please see http://www.contrastrebellion.com

**Comment by rhukster** [comment]
Funny high-contrast hurts my eyes :)  I'll take this under advisement.  Thanks!

**Comment by frostbitten** [comment]
Just throwing in my two cents because this issue intrigued me.
It does seem a bit too low contrast looking at the learn site, but that is not to say it's not close (or that super high contrast should be the go-to). I noted that the body font is set to a light 300 weight as well as with a color of `#777`.

I would suggest, since the text is already lightened by the weight, to use `#373737` for the `body` as it's dark enough without going to full black but retaining `#777` for `strong` elements

preview
![image](https://cloud.githubusercontent.com/assets/593791/14872033/278b7b72-0cb6-11e6-9412-88ee8dc4d7af.png)

**Comment by rhukster** [comment]
I think this is a good compromise for retina and non-retina displays.  #444 is a bit dark for my taste, but still looks good. And readability is more important in documentation that prettyness :)
