### ISSUE TITLE
Documentation on blueprints.yaml

### ISSUE THREAD

**Issue by msjyoo** [getgrav/grav-learn#54]
A documentation on blueprints.yaml is needed. It is recommended that this file is created, but nowhere does it say what it is used for, and how to use this file.

**Comment by w00fz** [comment]
Yeah I'm actually working on it right now. The blueprints don't have any use yet, hence the missing documentation. Although starting with the next version and forward they will serve a great part for themes and plugins, that's why we are only documenting now.
I'll link my commit here when I'm done so you can have a preview of it :)

Thanks.

**Comment by w00fz** [comment]
Just pushed some docs about Blueprints @ a714610a. This will appear publicly at http://learn.getgrav.org once we release the new version of Grav.
