### ISSUE TITLE
Update php5-fpm in the Nginx instructions

### ISSUE THREAD

**Issue by MelvinLoos** [getgrav/grav-learn#789]
I noticed that the "Web Servers & Hosting ->  Web/App Servers ->  Nginx" docs still reference php5-fpm in their installation instructions. This got me a bit worried about the state of this project but that might be another discussion. 

What I did want to do is suggest that this might be a problem. Since PHP 5.6 has been [out of official support since 31 Dec 2018](https://www.php.net/eol.php) and all main linux distributions have also stopped supporting it as far as I know. So I think when someone follows these instructions they for sure won't find php5-fpm and maybe run into other problems.

So I could send in a merge request just for changing php5-fpm to php-fpm but I will have to review the rest of the docs to know if anything else needs to change. Any suggestions are welcome.

**Comment by ricardo118** [comment]
yeah i think its just an out of date docs, grav works great in php7.4

**Comment by MelvinLoos** [comment]
Yes I understand that, because there would be more people complaining if it didn't. But that was not the point I wanted to make with my first sentence. I was just pointing out that out of date documentation like that could give of the wrong signals to newcomers like myself. It could just be an oversight but can also mean updates aren't that frequent on this project.

Anyhow like I said that is a different discussion. What this issue is about is, like the title says, updating instructions to a new PHP version. So to make it even clearer I will boil it down to one question.
**Should I send in a merge request changing just this one reference of php5-fpm or do we need to review the rest of the instructions on other outdated information ?**

Frankly I was only just checking out this project but wouldn't mind spending a bit of volunteer time on it. However I wasn't planning on spending a lot of hours on it because I am not actively using it in a project right now.

**Comment by ricardo118** [comment]
ive pushed the update on php7. Nginx docs was one of the first docs and was a little out of date. Linode one for example is much more recent and is using a better version. 

grav 1.7 release is requiring php7.1+ now.

Regarding the project, its very actively developed as you can see here https://github.com/getgrav/grav/releases not just 10 days ago the latest release. The team is hard at work getting 1.7 version ready for launch and then there will be a massive docs update since version 1.7 has many improvements and changes from 1.6. That said, any help fixing docs is always greatly appreciated so if you come across any either hit the `edit` button directly on the docs page or make another issue here its all good
